version: '1'

services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    restart: unless-stopped
    networks:
      - backend

networks:
  backend: