apiVersion: apps/v1
kind: Deployment
metadata:
  name: algorithm-service-deployment
spec:
  selector:
    matchLabels:
      app: algorithm-service
  replicas: 1
  template:
    metadata:
      labels:
        app: algorithm-service
    spec:
      containers:
        - name: algorithm-service
          image: kevdev0247/proofster-algorithm:v1.0
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: algorithm-service
spec:
  selector:
    app: algorithm-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
