"""empty message

Revision ID: 0c478ada5c8f
Revises: 580fc4b671f2
Create Date: 2023-01-22 23:08:30.316041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c478ada5c8f'
down_revision = '580fc4b671f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('formula')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formula',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_conclusion', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_binary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_unary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_function', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_variable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('left', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('right', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('connective', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantifier', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantifier_variable', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('negation', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('function_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('inside', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='formula_pkey')
    )
    # ### end Alembic commands ###
