"""empty message

Revision ID: 580fc4b671f2
Revises: 0f140a3e6b5f
Create Date: 2023-01-22 22:47:54.676565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580fc4b671f2'
down_revision = '0f140a3e6b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_conclusion', sa.Boolean(), nullable=True),
    sa.Column('is_binary', sa.Boolean(), nullable=True),
    sa.Column('is_unary', sa.Boolean(), nullable=True),
    sa.Column('is_function', sa.Boolean(), nullable=True),
    sa.Column('is_variable', sa.Boolean(), nullable=True),
    sa.Column('left', sa.BigInteger(), nullable=True),
    sa.Column('right', sa.BigInteger(), nullable=True),
    sa.Column('connective', sa.Integer(), nullable=True),
    sa.Column('quantifier', sa.Integer(), nullable=True),
    sa.Column('quantifier_variable', sa.BigInteger(), nullable=True),
    sa.Column('negation', sa.Boolean(), nullable=True),
    sa.Column('function_name', sa.String(), nullable=True),
    sa.Column('inside', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.drop_table('formula')
    # ### end Alembic commands ###
