"""empty message

Revision ID: f641649afb9b
Revises: f6a73a791803
Create Date: 2023-01-23 00:29:00.590875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f641649afb9b'
down_revision = 'f6a73a791803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formula', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_atom_inside', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('variable_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formula', schema=None) as batch_op:
        batch_op.drop_column('variable_name')
        batch_op.drop_column('has_atom_inside')

    # ### end Alembic commands ###
