"""empty message

Revision ID: f6a73a791803
Revises: 0c478ada5c8f
Create Date: 2023-01-22 23:39:36.868107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a73a791803'
down_revision = '0c478ada5c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_conclusion', sa.Boolean(), nullable=True),
    sa.Column('is_binary', sa.Boolean(), nullable=True),
    sa.Column('is_unary', sa.Boolean(), nullable=True),
    sa.Column('is_function', sa.Boolean(), nullable=True),
    sa.Column('is_variable', sa.Boolean(), nullable=True),
    sa.Column('left', sa.BigInteger(), nullable=True),
    sa.Column('right', sa.BigInteger(), nullable=True),
    sa.Column('connective', sa.Integer(), nullable=True),
    sa.Column('quantifier', sa.Integer(), nullable=True),
    sa.Column('quantifier_variable', sa.BigInteger(), nullable=True),
    sa.Column('negation', sa.Boolean(), nullable=True),
    sa.Column('function_name', sa.String(), nullable=True),
    sa.Column('inside', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    op.drop_table('formula')
    # ### end Alembic commands ###
